// <auto-generated />
using MagicDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicDbContext.Migrations
{
    [DbContext(typeof(MagicDbContext))]
    partial class MagicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicDbContext.Alias", b =>
                {
                    b.Property<int>("AliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AliasId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("AliasId");

                    b.ToTable("Alias", "base");
                });

            modelBuilder.Entity("MagicDbContext.Element", b =>
                {
                    b.Property<int>("ElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementId"));

                    b.Property<int>("ElementEnum")
                        .HasColumnType("int");

                    b.Property<int?>("MainSymbolId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ElementId");

                    b.HasIndex("MainSymbolId");

                    b.ToTable("Element", "element");
                });

            modelBuilder.Entity("MagicDbContext.ElementAlias", b =>
                {
                    b.Property<int>("ElementAliasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementAliasId"));

                    b.Property<int>("AliasId")
                        .HasColumnType("int");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.HasKey("ElementAliasId");

                    b.HasIndex("AliasId");

                    b.HasIndex("ElementId");

                    b.ToTable("ElementAlias", "element");
                });

            modelBuilder.Entity("MagicDbContext.ElementPlanetaryCorrespondence", b =>
                {
                    b.Property<int>("CorrespondenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorrespondenceId"));

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<int>("PlanetId")
                        .HasColumnType("int");

                    b.HasKey("CorrespondenceId");

                    b.HasIndex("ElementId");

                    b.HasIndex("PlanetId");

                    b.ToTable("ElementPlanetaryCorrespondence", "element");
                });

            modelBuilder.Entity("MagicDbContext.ElementSymbol", b =>
                {
                    b.Property<int>("ElementSymbolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElementSymbolId"));

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<int>("SymbolId")
                        .HasColumnType("int");

                    b.HasKey("ElementSymbolId");

                    b.HasIndex("ElementId");

                    b.HasIndex("SymbolId");

                    b.ToTable("ElementSymbol", "element");
                });

            modelBuilder.Entity("MagicDbContext.Number", b =>
                {
                    b.Property<int>("NumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumberId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("NumberId");

                    b.ToTable("Number", "base");
                });

            modelBuilder.Entity("MagicDbContext.Planet", b =>
                {
                    b.Property<int>("PlanetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanetId"));

                    b.Property<bool>("IsClassical")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("PlanetEnum")
                        .HasColumnType("int");

                    b.Property<int?>("SymbolId")
                        .HasColumnType("int");

                    b.HasKey("PlanetId");

                    b.HasIndex("SymbolId");

                    b.ToTable("Planet", "base");
                });

            modelBuilder.Entity("MagicDbContext.Symbol", b =>
                {
                    b.Property<int>("SymbolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SymbolId"));

                    b.Property<string>("Glyph")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NVARCHAR(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SymbolId");

                    b.ToTable("Symbol", "base");
                });

            modelBuilder.Entity("MagicDbContext.Element", b =>
                {
                    b.HasOne("MagicDbContext.Symbol", "MainSymbol")
                        .WithMany()
                        .HasForeignKey("MainSymbolId");

                    b.Navigation("MainSymbol");
                });

            modelBuilder.Entity("MagicDbContext.ElementAlias", b =>
                {
                    b.HasOne("MagicDbContext.Alias", "Alias")
                        .WithMany()
                        .HasForeignKey("AliasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagicDbContext.Element", "Element")
                        .WithMany("Aliases")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alias");

                    b.Navigation("Element");
                });

            modelBuilder.Entity("MagicDbContext.ElementPlanetaryCorrespondence", b =>
                {
                    b.HasOne("MagicDbContext.Element", "Element")
                        .WithMany("PlanetaryCorrespondences")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagicDbContext.Planet", "Planet")
                        .WithMany()
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("MagicDbContext.ElementSymbol", b =>
                {
                    b.HasOne("MagicDbContext.Element", "Element")
                        .WithMany("OtherSymbols")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagicDbContext.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("MagicDbContext.Planet", b =>
                {
                    b.HasOne("MagicDbContext.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("MagicDbContext.Element", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("OtherSymbols");

                    b.Navigation("PlanetaryCorrespondences");
                });
#pragma warning restore 612, 618
        }
    }
}
